# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/sds/overcommit/blob/master/config/default.yml
#
# At the topmost level of this YAML file is a key representing type of hook
# being run (e.g. pre-commit, commit-msg, etc.). Within each type you can
# customize each hook, such as whether to only run it on certain files (via
# `include`), whether to only display output if it fails (via `quiet`), etc.
#
# For a complete list of hooks, see:
# https://github.com/sds/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/sds/overcommit#configuration
#
---
CommitMsg:
  ALL:
    on_warn: fail
  CapitalizedSubject:
    enabled: false
  MessageFormat:
    enabled: true
    description: 'Check commit message match conventional format'
    expected_pattern_message: '<type>(<optional scope>): <description>'
    pattern: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z0-9]+\))?(\!)?: (.+)$'
    sample_message: 'chore(deps): bump version'

PreCommit:
  ALL:
    on_warn: fail
  RuboCop:
    enabled: true
  YamlLint:
    enabled: true

PrePush:
  ALL:
    on_warn: fail
